### ISSUE TITLE
[Идея]: Сортировка в хранилище дисков ботаники

### ISSUE THREAD

**Issue by SuhEugene** [SS13-Extended/Paradise#49]
**Описание идеи:**
> ДОБАВЬТЕ СОРТИРОВКУ ПО АЛФАВИТУ В ЙОБАННОЕ ХРАНИЛИЩЕ ДИСКОВ ДЛЯ БОТАНИКА

**Comment by DanielLavrushin** [comment]
привет, @SuhEugene 
глянь мой ПР, может так пойдет?
